base/urls.py
from django.urls import path
from base import views
from django.contrib.auth.views import LogoutView

app_name = 'base'

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='base:login'), name='logout'),
    path('register/', views.RegisterPage.as_view(), name='register'),
    path('', views.TaskList.as_view(), name='tasks'),
    path('task/<int:pk>/', views.TaskDetail.as_view(), name='task'),
    path('create-task/', views.TaskCreate.as_view(), name='task-create'),
    path('task-update/<int:pk>/', views.TaskUpdate.as_view(), name='task-update'),
    path('task-delete/<int:pk>/', views.TaskDelete.as_view(), name='task-delete'),
]

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Task(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    complete = models.BooleanField(default=False)
    create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta():
        ordering = ['complete']

##

base/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.http import HttpResponse
from .models import Task
# Create your views here.


class CustomLoginView(LoginView):
    fields = '__all__'
    template_name = 'base/login.html'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('base:tasks')


class RegisterPage(FormView):
    template_name = 'base/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('base:tasks')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage, self).form_valid(form)

    """
        def get(self, *args, **kwargs):
        if self.request.user.is__authenticated:
            return redirect('base:tasks')
        return super(RegisterPage, self).get(*args, **kwargs)
    """


class TaskList(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = 'tasks'

    def get_context_data(self, **kwargs):  # user can see only their data
        context = super().get_context_data(**kwargs)
        context['tasks'] = context['tasks'].filter(user=self.request.user)
        context['count'] = context['tasks'].filter(complete=False).count()
        # return context

        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['tasks'] = context['tasks'].filter(
                title__startswith=search_input)

        context['search_input'] = search_input
        return context


class TaskDetail(LoginRequiredMixin, DetailView):
    model = Task
    context_object_name = 'task'
    template_name = 'base/task.html'


class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    fields = ['title', 'description', 'complete']
    # tasks here is url name ,check .urls.py file
    success_url = reverse_lazy('base:tasks')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TaskCreate, self).form_valid(form)


class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    fields = '__all__'
    success_url = reverse_lazy('base:tasks')


class TaskDelete(LoginRequiredMixin, DeleteView):
    model = Task
    context_object_name = 'task'
    success_url = reverse_lazy('base:tasks')


"""
def tasklist(request):
    return HttpResponse('To Do List')
"""

base/templates/base/login.html
<h1>Login</h1>

<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Login">
</form>

<p>Don't have an account? <a href="{% url 'base:register' %}">Register</a></p>

base/templates/base/register.html
<h1>Register</h1>

<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Register">
</form>

<p>Already have an account? <a href="{% url 'base:register' %}"></a>Login</a></p>

base/templates/base/task.html
<h1>Task: {{task}}</h1>

base/templates/base/task_confirm_delete.html
<a href="{% url 'base:tasks' %}">Go Back</a>
<form method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete this task? "{{task}}"</p>
    <input type="submit" value="Delete"/>
</form>

base/templates/base/task_form.html
<h3>Task Form</h3>
<a href ="{% url 'base:tasks' %}">Go back</a>
<form method="POST" action=""> 
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

base/templates/base/task_list.html
{% if request.user.is_authenticated %}
    <p>{{request.user}}</p>
    <a href="{% url 'base:logout' %}">Logout</a>
{% else %}
<a href="{% url 'base:login' %}">Login</a>
{% endif %}
<h1>My To Do List</h1>
<a href="{% url 'base:task-create' %}">Add Task</a>

<form method="GET">
    <input type='text' name='search-area' value="{{search_input}}">
    <input type="submit" value="Search">
</form>
<table>
    <tr>
        <th>Item</th>
        <th>Link</th>
        <th>Edit</th>
        <th></th>
        <th>Delete</th>
    </tr>
    {% for task in tasks %}
    <tr>
        <td>{{task.title}}</td>
        <td><a href="{% url 'base:task' task.id %}">View</a></td>
        <td><a href="{% url 'base:task-update' task.id %}">Edit</a></td>
        <td></td>
        <td><a href="{% url 'base:task-delete' task.id %}">Delete</a></td>
    </tr>
    {% empty %}
        <h3>No items in list</h3>
    {% endfor %}
</table>